version: 2

defaults: &defaults
  working_directory: /tmp/crd-image
  environment:
    GOOGLE_COMPUTE_ZONE: us-central1-a
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/crd-image/workspace/packer-builder.json

jobs:

  setup:
    <<: *defaults
    docker:
      - image: vsseclab/circlecihastack
    steps:
      - checkout
      - run: mkdir -p workspace
      - run:
          name: set up service account keys
          command: echo ${GCLOUD_SERVICE_KEY} > workspace/packer-builder.json
      - persist_to_workspace:
          root: workspace
          paths:
            - packer-builder.json

  unit:
    <<: *defaults
    docker:
      - image: vsseclab/circlecihastack
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/crd-image/workspace
      - run:
          name: Run some checks to ensure the image is ready to build
          command: COMMIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7) make unit
    
  build:
    <<: *defaults
    docker:
      - image: vsseclab/circlecihastack
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/crd-image/workspace
      - run:
          name: Build and test image
          command: cd packer && COMMIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7) packer build desktop.json

workflows:
  version: 2
  image:
    jobs:
      - setup
      - unit:
          requires:
            - setup
          filters:
            branches:
              only: main
      - build:
          requires:
            - unit
          filters:
            branches:
              only: main
